Install :)
derek-duncan/postcss-responsify pull request #1
Opened 2017-06-23 19:42 UTC by terrillo

2017-06-23 20:47 UTC, derek-duncan requested changes
Noice. This is essential to _every_ npm package. Thanks!

2017-06-23 20:47 UTC, derek-duncan commented on README.md
> +npm install postcss-responsify --save
We should save as a dev dependency. `npm install postcss-responsify --save-dev`

2017-06-23 20:54 UTC, terrillo commented
@derek-duncan updated

2017-06-24 03:06 UTC, terrillo reviewed
Ready for review

2017-06-24 11:25 UTC, merged